# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_app', '0002_auto_20181018_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_login_app',
            new_name='User',
        ),
    ]
