# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-18 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0002_auto_20181018_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default=('big', 'Expert', 'smart', 'Ingenious'), max_length=255),
            preserve_default=False,
        ),
    ]
